### ISSUE TITLE
null reference

### ISSUE THREAD

**Issue by jrit** [AndyMcKenna/NopCommerce_FirstData#1]
In ProcessPayment, there is a check for whether the billing address id exists, but it then assumes that country id and state id exist, which in some configurations are potentially null.

Reference line
https://github.com/AndyMcKenna/NopCommerce_FirstData/blob/608b0e81353cae6d77aab04bfcd1de60d9d405a3/Plugin/FirstDataPaymentProcessor.cs#L258

Suggestion would be to check that country and state ids have values before using `.Value`

**Comment by AndyMcKenna** [comment]
You're absolutely right, thanks!
